schema: "classroom50/repo-config/v1"
classroom: "insy7314-2026-g3"
assignment: "insy7314-2026-hustlehub-plus-part1"
owner:
  username: "Maximus0305"
  id: 162804000
  accepted_at: "2026-09-03T13:20:29Z"
